name: Frontend Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'client/package-lock.json'
    
    - name: Clean up old config
      run: |
        cd client
        rm -f jest.config.js
    
    - name: Install dependencies
      run: |
        cd client
        npm install
    
    - name: Run tests
      run: |
        cd client
        npm test -- --watchAll=false --config=jest.config.cjs
    
    - name: Build
      run: |
        cd client
        npm run build 